### ISSUE TITLE
Cannot open JiveXML files through the browser in Firefox

### ISSUE THREAD

**Issue by EdwardMoyse** [ATLAS-experiment/PhoenixATLAS#13]
I tried to open the following file: /HWW/VBF/JiveXML_VBF_6_359541_2089686122.xml from the server, but it doesn't work (at least with Firefox).

In the console I see:
`Blocked loading mixed active content “http://phoenixatlas.web.cern.chtlas/data/event_data/HWW/VBF/JiveXML_VBF_6_359541_2089686122.xml”`

So it's related to this:
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

This WAS working before! So either Firefox changed something or we did (I've not had time to look into this at all yet).

**Comment by EdwardMoyse** [comment]
Just checked this with Chrome and the error is a bit more useful:
```
polyfills.d4db5674f0a2f29e.js:1 Mixed Content: 
The page at 'https://phoenixatlas.web.cern.ch/PhoenixATLAS/' was loaded over HTTPS, but requested an insecure resource 
'http://phoenixatlas.web.cern.ch/data/event_data/HWW/VBF/JiveXML_VBF_1_337705_1829797121.xml'. This request has been blocked; the content must be served over HTTPS.
```
So the problem is that we are internally asking for http in the file browser. @9inpachi do you know where this is? If not I'll have a look.

**Comment by 9inpachi** [comment]
You could specify the `apiURL` with an absolute URL with https and that should work.
