### ISSUE TITLE
Local browser not working

### ISSUE THREAD

**Issue by EdwardMoyse** [ATLAS-experiment/PhoenixATLAS#16]
I just did a fresh install and when I click on the browse files icon, I get:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/6764617/168995187-4733d77c-99f2-4647-8067-307f1eaf4679.png">
And:
<img width="544" alt="Screenshot 2022-05-18 at 10 34 36" src="https://user-images.githubusercontent.com/6764617/168995537-4089e6ee-999b-41d6-bbe5-d0f8cdd140f3.png">

**Comment by EdwardMoyse** [comment]
`api` directory is there as expected:
```
emoyse@Edwards-MacBook-Pro PhoenixATLAS % ls -lht
total 648
drwxr-xr-x  589 emoyse  staff    18K May 18 10:23 node_modules
-rw-r--r--    1 emoyse  staff   1.4K May 18 10:23 package.json
-rw-r--r--    1 emoyse  staff   298K May 18 10:23 yarn.lock
-rw-r--r--    1 emoyse  staff   1.6K May 18 10:19 README.md
-rw-r--r--    1 emoyse  staff   503B Mar 17 09:25 tsconfig.json
-rw-r--r--    1 emoyse  staff   190B Mar 17 09:25 tsconfig.app.json
drwxr-xr-x   10 emoyse  staff   320B Mar 17 09:25 src
drwxr-xr-x    4 emoyse  staff   128B Mar 17 09:25 guides
drwxr-xr-x    4 emoyse  staff   128B Mar 17 09:25 api
-rw-r--r--    1 emoyse  staff   4.2K Mar 17 09:25 angular.json
```

**Comment by 9inpachi** [comment]
The `apiURL` needs to be set relative to the path the application is deployed to.

https://github.com/ATLAS-experiment/PhoenixATLAS/blob/master/src/app/pages/atlas/atlas.component.ts#L21

If the deployed Phoenix exists in `phoenix-dist` for example, the the api files will go to `phoenix-dist/api` and the `apiURL` will be set to `api/read-files.php`.

**Comment by EdwardMoyse** [comment]
Fixed! Thanks @9inpachi
